environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.15"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.15"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.13.1"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy==1.15"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY: "numpy==1.15"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy>=1.15"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy>=1.15"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "32"
      NUMPY: "numpy>=1.15"

install:
  - "python --version"

build_script:
  - "pip install %NUMPY%"
  - "pip install pytest pytest-runner"
  - "pip install \"awkward>=0.11.0\""
  - "python -c \"import awkward; print(awkward.__version__)\""
  - "pytest -v tests"
